const PDFDocument = require("pdfkit");

const generateReport = async (req, res) => {

    try {

        const {
            patientName,
            disease,
            confidence,
            description,
            symptoms
        } = req.body;

        const doc = new PDFDocument({
            margin: 50,
            size: "A4"
        });

        res.setHeader(
            "Content-Type",
            "application/pdf"
        );

        res.setHeader(
            "Content-Disposition",
            "attachment; filename=HealthAI_Report.pdf"
        );

        doc.pipe(res);

        // ===================================
        // Header
        // ===================================

        doc
            .fontSize(26)
            .fillColor("#2563eb")
            .text("🏥 HealthAI", {
                align: "center"
            });

        doc
            .moveDown(0.5)
            .fontSize(18)
            .fillColor("#000000")
            .text("AI Disease Prediction Report", {
                align: "center"
            });

        doc.moveDown(2);

        // ===================================
        // Patient Information
        // ===================================

        doc
            .fontSize(16)
            .fillColor("#2563eb")
            .text("Patient Information");

        doc.moveDown(0.5);

        doc
            .fontSize(13)
            .fillColor("black")
            .text(`Patient Name : ${patientName}`);

        doc.text(`Date : ${new Date().toLocaleString()}`);

        doc.moveDown(1.5);

        // ===================================
        // Prediction
        // ===================================

        doc
            .fontSize(16)
            .fillColor("#2563eb")
            .text("Prediction Result");

        doc.moveDown(0.5);

        doc
            .fontSize(13)
            .fillColor("black")
            .text(`Disease : ${disease}`);

        doc.text(`Confidence : ${confidence}%`);

        doc.moveDown(1.5);

        // ===================================
        // Description
        // ===================================

        doc
            .fontSize(16)
            .fillColor("#2563eb")
            .text("Description");

        doc.moveDown(0.5);

        doc
            .fontSize(13)
            .fillColor("black")
            .text(description);

        doc.moveDown(1.5);

        // ===================================
        // Selected Symptoms
        // ===================================

        doc
            .fontSize(16)
            .fillColor("#2563eb")
            .text("Selected Symptoms");

        doc.moveDown(0.5);

        if (Array.isArray(symptoms) && symptoms.length > 0) {

            symptoms.forEach(symptom => {

                doc
                    .fontSize(13)
                    .fillColor("black")
                    .text("• " + symptom.replace(/_/g, " "));

            });

        } else {

            doc
                .fontSize(13)
                .fillColor("black")
                .text("No symptoms available.");

        }

        doc.moveDown(1.5);

        // ===================================
        // Recommendation
        // ===================================

        doc
            .fontSize(16)
            .fillColor("#2563eb")
            .text("General Recommendation");

        doc.moveDown(0.5);

        doc
            .fontSize(13)
            .fillColor("black")
            .text("• Drink plenty of water");

        doc.text("• Take proper rest");

        doc.text("• Eat healthy food");

        doc.text("• Take medicines only as prescribed by a doctor");

        doc.text("• Consult a qualified healthcare professional");

        doc.moveDown(2);

        // ===================================
        // Disclaimer
        // ===================================

        doc
            .fontSize(12)
            .fillColor("red")
            .text(
                "Disclaimer: This report is generated using an AI model and is intended only for informational purposes. It should not be considered a substitute for professional medical advice, diagnosis, or treatment."
            );

        doc.moveDown(2);

        // ===================================
        // Footer
        // ===================================

        doc
            .fontSize(11)
            .fillColor("gray")
            .text(
                "Generated by HealthAI • AI Healthcare Assistant",
                {
                    align: "center"
                }
            );

        doc.end();

    }

    catch (error) {

        console.log(error);

        res.status(500).json({
            message: "PDF Generation Failed"
        });

    }

};

module.exports = {
    generateReport
};