const PDFDocument = require("pdfkit");

function generateHealthReport(data, res) {

    const doc = new PDFDocument();

    // PDF response settings
    res.setHeader(
        "Content-Type",
        "application/pdf"
    );

    res.setHeader(
        "Content-Disposition",
        "attachment; filename=HealthAI_Report.pdf"
    );

    // Send PDF to browser
    doc.pipe(res);


    // Title
    doc
        .fontSize(22)
        .text("HealthAI", { align: "center" });


    doc
        .fontSize(14)
        .text("AI Healthcare Assistant Report", {
            align: "center"
        });


    doc.moveDown();


    // Patient Information
    doc.fontSize(16)
       .text("Patient Information");


    doc.fontSize(12)
       .text(`Name: ${data.name}`)
       .text(`Age: ${data.age}`)
       .text(`Gender: ${data.gender}`);


    doc.moveDown();


    // Prediction Information
    doc.fontSize(16)
       .text("Health Prediction");


    doc.fontSize(12)
       .text(`Symptoms: ${data.symptoms}`)
       .text(`Predicted Disease: ${data.disease}`)
       .text(`Confidence: ${data.confidence}%`);


    doc.moveDown();


    // Disease Information
    doc.fontSize(16)
       .text("Disease Information");


    doc.fontSize(12)
       .text(data.description);


    doc.moveDown();


    // Recommendations
    doc.fontSize(16)
       .text("Recommendations");


    doc.fontSize(12)
       .text(data.recommendations);


    doc.moveDown();


    doc.text(
        `Generated Date: ${new Date().toDateString()}`
    );


    doc.moveDown();


    doc.text(
        "Generated by HealthAI AI Assistant",
        {
            align:"center"
        }
    );


    // Finish PDF
    doc.end();
}


module.exports = generateHealthReport;